### ISSUE TITLE
translate commands crash because of a request issue

### ISSUE THREAD

**Issue by ArtOfCode-** [ProgramFOX/SE-Chatbot-Builtins#4]
Running KarmaBot in [WB Robots](http://chat.stackexchange.com/rooms/35580/worldbuildings-robots), with a Yandex API key in the correct file.

`detect_lang` fails with the error message `get() takes 1 positional argument but 2 were given` (`get()` being `requests.get`).

translate.py: 141

I haven't been able to figure out the cause.

I believe @overactor was the original dev of this module?

**Comment by thomas-daniels** [comment]
I originally implemented this. I'll take a look at this.

**Comment by ArtOfCode-** [comment]
Feel free to drop into the room I linked; I can give you access to the server it runs on to debug it.

**Comment by thomas-daniels** [comment]
The issue was an outdated version of requests.
