### ISSUE TITLE
Improve 'didyoumean' for nested commands

### ISSUE THREAD

**Issue by thomas-daniels** [ProgramFOX/SE-Chatbot-Builtins#5]
see http://chat.meta.stackexchange.com/transcript/message/5273678#5273678 messages below

**Comment by rik-degraaff** [comment]
This will require a minor (but breaking) change in SE-Chatbot as well: Adding start parameter to Chatbot.command().

**Comment by rik-degraaff** [comment]
@ProgramFOX I implemented this but can't figure out when to clear the suggestions, you got an idea?
